services:
  prometheus:
    image: prom/prometheus
    restart: always
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-storage:/prometheus:rw

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana:rw

  loki:
    image: grafana/loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - loki-storage:/loki:rw

  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 30

volumes:
  prometheus-storage:
  grafana-storage:
  loki-storage:
