scrape_configs:
  - job_name: prod
    # TODO: <http_config> to enable Basic Auth
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "api.study-up.site"
        labels:
          application: app-core

  - job_name: qa
    # TODO: <http_config> to enable Basic Auth
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "whitepiano-codeserver.pe.kr"
        labels:
          application: app-qa-core
