scrape_configs:
  - job_name: application
    metrics_path: /actuator/prometheus
    static_configs:
      - labels:
          application: app-qa-core
        targets: [ "whitepiano-codeserver.pe.kr:8081" ]

  - job_name: exporter
    static_configs:
      - targets: [ "whitepiano-codeserver.pe.kr:9100" ]
      - targets: [ "whitepiano-codeserver.pe.kr:9104" ]
      - targets: [ "whitepiano-codeserver.pe.kr:9216" ]
